# Resolver react_native_pods.rb
require_relative '../node_modules/react-native/scripts/react_native_pods.rb'
require_relative '../node_modules/@react-native-community/cocoapods/helpers.rb'

platform :ios, '13.0'
inhibit_all_warnings!

target 'RNAdvancedTP01' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,        # Legacy — Hermes désactivé
    :fabric_enabled => false,        # Legacy — Fabric désactivé
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
